objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CCA2_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CCA2_Account_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CCA2_Account_Goals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCA2_Goal__c</fullName>
        <label>CCA2_Goal</label>
        <referenceTo>CCA2_Goal__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>CCA2_Account_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Goal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Account Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Application_Goal__c.object
<CustomObject>
    <fields>
        <fullName>CCA2_Account_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CCA2_Account Goal</label>
        <referenceTo>CCA2_Account_Goal__c</referenceTo>
        <relationshipName>CCA2_Application_Goals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCA2_Application__c</fullName>
        <label>CCA2_Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>CCA2_Application_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_X_Score__c</fullName>
        <description>The final percentage match for this application to this goal</description>
        <formula>if ( Exclude__c, 0, (Total_Score__c /  CCA2_Account_Goal__r.CCA2_Goal__r.Max_Goal_Score__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The final percentage match for this application to this goal</inlineHelpText>
        <label>Total % Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Application Goal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Application Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Goal__c.object
<CustomObject>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AppsByGoalController.cls
/*
            Name        :     AppsByGoalController
            Author      :     
            Date        :     28 Jan 2015
            Description :     Controller to show the "Apps By Goal" detail on the Account Goal Object
*/
public class AppsByGoalController{
    public List<CCA2_Application_Goal__c> applicationList {get;set;}
    public string goalName{get;set;}
    
    // Constructor
    public AppsByGoalController(){
        applicationList = new List<CCA2_Application_Goal__c>();
        String goalId =  Apexpages.currentPage().getParameters().get('goalid');
        String accId =  Apexpages.currentPage().getParameters().get('accid');
        if(goalId != null && goalId.trim().length()>0 && accId != null && accId.trim().length()>0){
            applicationList = [SELECT Id, CCA2_Application__r.Name, Total_X_Score__c, CCA2_Account_Goal__r.Account__c, CCA2_Account_Goal__r.CCA2_Goal__r.Name
                               FROM CCA2_Application_Goal__c 
                               WHERE CCA2_Account_Goal__r.CCA2_Goal__c = :goalId 
                               AND CCA2_Account_Goal__r.Account__c =: accId
                               Order By Total_X_Score__c DESC];
           
            if(applicationList.size()>0){
                goalName = applicationList[0].CCA2_Account_Goal__r.CCA2_Goal__r.Name;
            }
        }
    }
    
    public list<ModleData> getData(){
        list<ModleData> modleList = new list<ModleData>();
        for(CCA2_Application_Goal__c gScore : applicationList){             
             ModleData modelObj = new ModleData(''+gScore.CCA2_Application__r.Name, gScore.Total_X_Score__c);
             modleList.add(modelObj);
        }
        return modleList;
    }
    
    public class ModleData{
        public String appName{get;set;}
        public decimal percentageScore{get;set;}
        public ModleData(string applicationName, decimal score) {
            this.appName = applicationName;
            this.percentageScore = score != null ? score : 0;
        }
    }
}