objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CCA2_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Health</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CCA2_Account_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CCA2_Account_Goals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCA2_Goal__c</fullName>
        <label>CCA2_Goal</label>
        <referenceTo>CCA2_Goal__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>CCA2_Account_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Goal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Account Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Goal__c.object
<CustomObject>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CCA2_Question__c.object
<CustomObject>
    <fields>
        <fullName>Gate__c</fullName>
        <label>Gate</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CCA2_Response__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>CCA2_Application__r.Account__r.Name</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCA2_Application__c</fullName>
        <label>CCA2_Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>CCA2_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCA2_Question__c</fullName>
        <label>CCA2_Question</label>
        <referenceTo>CCA2_Question__c</referenceTo>
        <relationshipName>CCA2_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gate__c</fullName>
        <label>Gate</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Response</label>
    <nameField>
        <displayFormat>RESP-{0}</displayFormat>
        <label>CCA2_Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestAssignApplictionToGoalController.cls
@istest
public class TestAssignApplictionToGoalController{
    @istest
    public static void test(){
        String ownerid;
        ownerid = [select Id from Group where Name = 'unassigned' and Type = 'Queue' limit 1].id;
        
        //Creating Question
        CCA2_Question__c questionObject = new CCA2_Question__c (Type__c = 'Text', Name = 'New Question', Gate__c = 2, Sequence__c = 1);
        insert questionObject;
        
        //Creating Gole
        CCA2_Goal__c goalObject = new CCA2_Goal__c(Name = 'New Goal'); 
        insert goalObject;
        CCA2_Goal__c goalObject2 = new CCA2_Goal__c(Name = 'New Goal2'); 
        insert goalObject2;
        
        //Creating Account
        Account accountObject1 = new Account(Name = 'New Account1');
        insert accountObject1;
        
        //Creating AccountGoal
        CCA2_Account_Goal__c accGoalObj = new CCA2_Account_Goal__c (Account__c = accountObject1.id, CCA2_Goal__c = goalObject.Id);
        Insert accGoalObj;
        
        //Creating Application
        Application__c applicationObj1 = new Application__c(Account__c = accountObject1.id, Name = 'New Application', Description__c = 'New Application Description');
        insert applicationObj1;
        
        Application__c applicationObj2 = new Application__c(Account__c = accountObject1.id, Name = 'New Application2', Description__c = 'New Application Description');
        insert applicationObj2;
        
        //Creating Responce Record
        CCA2_Response__c responceRecord1 = new CCA2_Response__c(CCA2_Application__c = applicationObj1.id, CCA2_Question__c = questionObject.id, Gate__c = 1);
        insert responceRecord1;
        
        CCA2_Response__c responceRecord2 = new CCA2_Response__c(CCA2_Application__c = applicationObj2.id, CCA2_Question__c = questionObject.id, Gate__c = 2);
        insert responceRecord2;
        
        //Assign account id in pagereference
        ApexPages.currentPage().getParameters().put('accountId',accountObject1.id);
        
        AssignApplicationsToGoalsController obj = new AssignApplicationsToGoalsController();
        obj.selectedGate = '2';
        system.debug('Before list------->' + obj.modalAllList);
        obj.modalAllList[1].status = true;
        obj.modalAllList[1].excluded = true;
        obj.modalAllList[1].unsignedStatus = true;
        system.debug('After list------->' + obj.modalAllList);
        obj.assignedAll();
        obj.changeSelectList();
        //obj.unsignedApp = true;
        obj.changeSelectList();
        obj.next();
        obj.prev();
        obj.last();
        obj.first();
        obj.getPagePosition();
        obj.cancel();
    }
}