objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CCA2_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Best_Fit_Goal__c</fullName>
        <label>Best Fit Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Best_Goal_For_App_Number_Of_Questions__c</fullName>
        <label>Best Goal For App Number Of Questions</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Owner_of_the_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Owner of the Application</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Health</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CCA2_Account_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CCA2_Account_Goals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCA2_Goal__c</fullName>
        <label>CCA2_Goal</label>
        <referenceTo>CCA2_Goal__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>CCA2_Account_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Goal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Account Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question</description>
        <inlineHelpText>Question</inlineHelpText>
        <label>Question</label>
        <referenceTo>CCA2_Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>CCA2_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>ANS-{00000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Goal__c.object
<CustomObject>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CCA2_Goal_Question__c.object
<CustomObject>
    <fields>
        <fullName>CCA2_Goal__c</fullName>
        <label>CCA2_Goal</label>
        <referenceTo>CCA2_Goal__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>CCA2_Goal_Question</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCA2_Question__c</fullName>
        <label>CCA2_Question</label>
        <referenceTo>CCA2_Question__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>CCA2_Goal_Question</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Goal Question</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>CCA2_Goal Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goal Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Goal_Score__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <referenceTo>CCA2_Answer__c</referenceTo>
        <relationshipLabel>Scores By Goal</relationshipLabel>
        <relationshipName>Goal_Scores</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCA2_Goals__c</fullName>
        <label>CCA2_Goal</label>
        <referenceTo>CCA2_Goal__c</referenceTo>
        <relationshipLabel>Answer Scores</relationshipLabel>
        <relationshipName>CCA2_Goal_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Goal Score</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Goal Score  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goal Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Question__c.object
<CustomObject>
    <fields>
        <fullName>Gate__c</fullName>
        <label>Gate</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestAssigningtheQuestionsController.cls
@isTest
public class TestAssigningtheQuestionsController{
    @istest
    public static void test(){
        String ownerid;
        ownerid = [select Id from Group where Name = 'unassigned' and Type = 'Queue' limit 1].id;
        
        //Creating Account
        Account accountObject = new Account(Name = 'New Account');
        insert accountObject;
        
         // creating contact record.
        Contact contactObject = new Contact(LastName='TestContact',AccountId=accountObject.Id);
        insert contactObject;
        
        //Creating Gole
        CCA2_Goal__c goalObject = new CCA2_Goal__c(Name = 'New Goal');
        insert goalObject;
        
        
        //Creating AccountGoal
        CCA2_Account_Goal__c accGoalObj = new CCA2_Account_Goal__c (Account__c = accountObject.id, CCA2_Goal__c = goalObject.Id);
        Insert accGoalObj;
       
        
        //Creating Question
        CCA2_Question__c questionObject = new CCA2_Question__c (Sequence__c = 1.0,Type__c = 'Text', Name = 'New Question 1', Gate__c = 2);
        insert questionObject;
        
        //Creating goalQuestion
        CCA2_Goal_Question__c goalQuesObj = new CCA2_Goal_Question__c(CCA2_Goal__c = goalObject.id, CCA2_Question__c =  questionObject.id );
        insert goalQuesObj;
        
        //Creating Answer Object
        CCA2_Answer__c answerObject = new CCA2_Answer__c(Question__c = questionObject.id);
        insert answerObject;
        
        
        //Creating GoalScore Object
        CCA2_Goal_Score__c goalScoreObj = new CCA2_Goal_Score__c(Score__c = 5, CCA2_Goals__c = goalObject.id, Answer__c = answerObject.id);
        insert goalScoreObj;
        
        // creating application record.
        Application__c app = new Application__c();
        app.Name='Test Application';
        app.Account__c = accountObject.Id;
        app.Best_Fit_Goal__c ='test2';
        app.Business_Owner_of_the_Application__c = contactObject.Id;
        app.Best_Goal_For_App_Number_Of_Questions__c = 'test2';
        app.Classification__c  = 'test2';
        app.Type__c = 'Finance';    
        app.Description__c = 'tests2';             
        insert app;
        
        ApexPages.currentPage().getParameters().put('accid',accountObject.Id);
        AssigningtheQuestionsController ctrl = new AssigningtheQuestionsController();
        ctrl.fetchUnassignedQues();
        ctrl.updateData();
        ctrl.next();
        ctrl.first();
        ctrl.last();
        ctrl.getPagePosition();
        
        
    }
}