objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Best_Fit_Goal__c</fullName>
        <label>Best Fit Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Best_Goal_For_App_Number_Of_Questions__c</fullName>
        <label>Best Goal For App Number Of Questions</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CCA2_Account_Goal__c.object
<CustomObject>
    <fields>
        <fullName>CCA2_Goal__c</fullName>
        <label>CCA2_Goal</label>
        <referenceTo>CCA2_Goal__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>CCA2_Account_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Goal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Account Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Application_Goal__c.object
<CustomObject>
    <fields>
        <fullName>CCA2_Account_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CCA2_Account Goal</label>
        <referenceTo>CCA2_Account_Goal__c</referenceTo>
        <relationshipName>CCA2_Application_Goals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCA2_Application__c</fullName>
        <label>CCA2_Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>CCA2_Application_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Answered_Questions_Formula__c</fullName>
        <formula>IF( Exclude__c , 0 ,Number_of_Answered_Questions__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Answered Questions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_X_Score__c</fullName>
        <description>The final percentage match for this application to this goal</description>
        <formula>if ( Exclude__c, 0, (Total_Score__c /  CCA2_Account_Goal__r.CCA2_Goal__r.Max_Goal_Score__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The final percentage match for this application to this goal</inlineHelpText>
        <label>Total % Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Application Goal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Application Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Goal__c.object
<CustomObject>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ApplicationGoalHelper.cls
public with sharing class ApplicationGoalHelper {

    public static void MarkAsCompleted(set<string> appIds) {
        list<Application__c> Applications = [SELECT Id, Completed__c, //Best_Fit_Goal__c,
                                             (SELECT Id, Completed__c, CCA2_Application__c, Total_X_Score__c, CCA2_Account_Goal__r.CCA2_Goal__r.Name
                                              FROM CCA2_Application_Goals__r 
                                              ORDER BY Total_X_Score__c DESC)
                                             FROM Application__c
                                             WHERE Id IN: appIds];
                                             
        Map<String,Application__c> applicationMap = new Map<string,Application__c>([SELECT Id, Completed__c, //Best_Fit_Goal__c,
                                                                                 (SELECT Id,Number_of_Answered_Questions_Formula__c, CCA2_Account_Goal__r.CCA2_Goal__r.Name
                                                                                  FROM CCA2_Application_Goals__r 
                                                                                  ORDER BY Number_of_Answered_Questions_Formula__c DESC)
                                                                                 FROM Application__c
                                                                                 WHERE Id IN: appIds]);
    
        if(Applications.size()>0){
            for(Application__c app : Applications){
                if(app.CCA2_Application_Goals__r.size()>0){
                    app.Completed__c = true;                    
                    for(CCA2_Application_Goal__c appGoal : app.CCA2_Application_Goals__r){
                        if(!appGoal.Completed__c){
                            app.Completed__c = false;
                        }
                    }
                    if(app.Completed__c){
                        app.Best_Fit_Goal__c = app.CCA2_Application_Goals__r[0].Total_X_Score__c>0 ? app.CCA2_Application_Goals__r[0].CCA2_Account_Goal__r.CCA2_Goal__r.Name : 'Keep on premise';
                        
                        if(applicationMap.containskey(app.Id) &&  applicationMap.get(app.Id).CCA2_Application_Goals__r.size()>0){
                            Application__c tempApp = applicationMap.get(app.Id);
                            app.Best_Goal_For_App_Number_Of_Questions__c = tempApp.CCA2_Application_Goals__r[0].Number_of_Answered_Questions_Formula__c > 0 ? tempApp.CCA2_Application_Goals__r[0].CCA2_Account_Goal__r.CCA2_Goal__r.Name : 'Keep on premise';
                        }
                    }
                }
            }
            update Applications;
        }
    }
}