objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CCA2_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Best_Fit_Goal__c</fullName>
        <label>Best Fit Goal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Best_Goal_For_App_Number_Of_Questions__c</fullName>
        <label>Best Goal For App Number Of Questions</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Owner_of_the_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Owner of the Application</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Health</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CCA2_Account_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CCA2_Account_Goals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCA2_Goal__c</fullName>
        <label>CCA2_Goal</label>
        <referenceTo>CCA2_Goal__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>CCA2_Account_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Unique Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Goal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Account Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Answer__c.object
<CustomObject>
    <fields>
        <fullName>High_Value__c</fullName>
        <label>High Value</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low_Value__c</fullName>
        <label>Low Value</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question</description>
        <inlineHelpText>Question</inlineHelpText>
        <label>Question</label>
        <referenceTo>CCA2_Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>CCA2_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>ANS-{00000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Application_Goal__c.object
<CustomObject>
    <fields>
        <fullName>CCA2_Account_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CCA2_Account Goal</label>
        <referenceTo>CCA2_Account_Goal__c</referenceTo>
        <relationshipName>CCA2_Application_Goals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCA2_Application__c</fullName>
        <label>CCA2_Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>CCA2_Application_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Unique Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Application Goal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Application Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Application_Goal_Score__c.object
<CustomObject>
    <fields>
        <fullName>CCA2_Application_Goal__c</fullName>
        <label>CCA2_Application Goal</label>
        <referenceTo>CCA2_Application_Goal__c</referenceTo>
        <relationshipName>CCA2_Application_Goal_Scores</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCA2_Response__c</fullName>
        <label>CCA2_Response</label>
        <referenceTo>CCA2_Response__c</referenceTo>
        <relationshipName>CCA2_Application_Goal_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>The question for this applicationGoalScore</description>
        <formula>CCA2_Response__r.CCA2_Question__r.Name</formula>
        <inlineHelpText>The question for this applicationGoalScore</inlineHelpText>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Application Goal Score</label>
    <nameField>
        <displayFormat>AGS-{00000}</displayFormat>
        <label>CCA2_Application Goal Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Goal Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Goal__c.object
<CustomObject>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CCA2_Goal_Question__c.object
<CustomObject>
    <fields>
        <fullName>CCA2_Goal__c</fullName>
        <label>CCA2_Goal</label>
        <referenceTo>CCA2_Goal__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>CCA2_Goal_Question</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCA2_Question__c</fullName>
        <label>CCA2_Question</label>
        <referenceTo>CCA2_Question__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>CCA2_Goal_Question</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Unique Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Goal Question</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>CCA2_Goal Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goal Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Goal_Score__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <referenceTo>CCA2_Answer__c</referenceTo>
        <relationshipLabel>Scores By Goal</relationshipLabel>
        <relationshipName>Goal_Scores</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCA2_Goals__c</fullName>
        <label>CCA2_Goal</label>
        <referenceTo>CCA2_Goal__c</referenceTo>
        <relationshipLabel>Answer Scores</relationshipLabel>
        <relationshipName>CCA2_Goal_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Unique Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Goal Score</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Goal Score  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goal Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Question__c.object
<CustomObject>
    <fields>
        <fullName>Gate__c</fullName>
        <label>Gate</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CCA2_Response__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>CCA2_Application__r.Account__r.Name</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCA2_Application__c</fullName>
        <label>CCA2_Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>CCA2_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCA2_Question__c</fullName>
        <label>CCA2_Question</label>
        <referenceTo>CCA2_Question__c</referenceTo>
        <relationshipName>CCA2_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gate__c</fullName>
        <label>Gate</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Unique Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Response</label>
    <nameField>
        <displayFormat>RESP-{0}</displayFormat>
        <label>CCA2_Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AnsweringQuestionsCtrlTest.cls
@isTest
public class AnsweringQuestionsCtrlTest{

    @testSetup static void setupTestData(){
       
    
    
    }

    public static testMethod void unitTest(){
         // creating account record.
        Account acc = new Account(Name='TestAccount');
        insert acc;
        
        // creating contact record.
        Contact con = new Contact(LastName='TestContact',AccountId=acc.Id);
        insert con;
        
        // creating application record.
        Application__c app = new Application__c();
        app.Name='Test Application';
        app.Account__c = acc.Id;
        app.Best_Fit_Goal__c ='test';
        app.Business_Owner_of_the_Application__c = con.Id;
        app.Best_Goal_For_App_Number_Of_Questions__c = 'test';
        app.Classification__c  = 'test';
        app.Type__c = 'Finance';    
        app.Description__c = 'tests';             
        insert app;
        
        //Creating Gole
        CCA2_Goal__c goalObject = new CCA2_Goal__c(Name = 'New Goal');
        insert goalObject;
        
        // creating account goal record.
        CCA2_Account_Goal__c accgoalObject = new CCA2_Account_Goal__c();
        accgoalObject.Account__c = acc.Id;
        accgoalObject.CCA2_Goal__c = goalObject.Id;
        accgoalObject.Unique_Id__c = 'ag101';
        insert accgoalObject;
        
        
        // creating application goal record.
        CCA2_Application_Goal__c appgoalObject = new CCA2_Application_Goal__c();
        appgoalObject.CCA2_Application__c = app.Id;
        appgoalObject.Unique_Id__c = '111';
        appgoalObject.CCA2_Account_Goal__c = accgoalObject.Id;
        insert appgoalObject;
        
        // creating question records.
        CCA2_Question__c questionObject = new CCA2_Question__c (Sequence__c = 1.0,Type__c = 'Picklist', Name = 'New Question', Gate__c = 2);
        insert questionObject;      
        
        //Creating goalQuestion
        CCA2_Goal_Question__c goalQuesObj = new CCA2_Goal_Question__c(CCA2_Goal__c = goalObject.id, CCA2_Question__c =  questionObject.id );
        insert goalQuesObj;
        
        //Creating Answer Object
        CCA2_Answer__c answerObject = new CCA2_Answer__c(Question__c = questionObject.id,High_Value__c=10,Low_Value__c=2);
        insert answerObject;
        
        CCA2_Answer__c answerObject2 = new CCA2_Answer__c(Question__c = questionObject.id,Low_Value__c=2);
        insert answerObject2;
        
        CCA2_Answer__c answerObject3 = new CCA2_Answer__c(Question__c = questionObject.id,High_Value__c=10);
        insert answerObject3;
        
        //Creating GoalScore Object
        CCA2_Goal_Score__c goalScoreObj = new CCA2_Goal_Score__c(Score__c = 5,Exclude__c=true, CCA2_Goals__c = goalObject.id, Answer__c = answerObject3.id);
        insert goalScoreObj;
   
        // creating response records.
        CCA2_Response__c responseObject = new CCA2_Response__c();
        responseObject.CCA2_Application__c = app.Id;
        responseObject.CCA2_Question__c    = questionObject.Id;
        responseObject.Answer__c = 'test';
        responseObject.Gate__c   = 1;
        responseObject.Unique_Id__c = '101';
        insert responseObject;
        
        CCA2_Application_Goal_Score__c ags = new  CCA2_Application_Goal_Score__c();
        ags.CCA2_Response__c = responseObject.Id;
        ags.CCA2_Application_Goal__c = appgoalObject.Id;
        insert ags;
        
        AnsweringQuestionsCtrl obj = new AnsweringQuestionsCtrl();
        obj.currentQuestion = questionObject.id;
        obj.showUnanswered = true;
        obj.changeQuestion();
        obj.showUnanswered();
        
        obj.saveRecords();
    }
    
    public static testMethod void unitTest2(){
        // creating account record.
        Account acc = new Account(Name='TestAccount');
        insert acc;
        
        // creating contact record.
        Contact con = new Contact(LastName='TestContact',AccountId=acc.Id);
        insert con;
        
        // creating application record.
        Application__c app = new Application__c();
        app.Name='Test Application';
        app.Account__c = acc.Id;
        app.Best_Fit_Goal__c ='test';
        app.Business_Owner_of_the_Application__c = con.Id;
        app.Best_Goal_For_App_Number_Of_Questions__c = 'test';
        app.Classification__c  = 'test';
        app.Type__c = 'Finance';    
        app.Description__c = 'tests';             
        insert app;
        
        //Creating Gole
        CCA2_Goal__c goalObject = new CCA2_Goal__c(Name = 'New Goal');
        insert goalObject;
        
        // creating account goal record.
        CCA2_Account_Goal__c accgoalObject = new CCA2_Account_Goal__c();
        accgoalObject.Account__c = acc.Id;
        accgoalObject.CCA2_Goal__c = goalObject.Id;
        accgoalObject.Unique_Id__c = 'ag101';
        insert accgoalObject;
        
        
        // creating application goal record.
        CCA2_Application_Goal__c appgoalObject = new CCA2_Application_Goal__c();
        appgoalObject.CCA2_Application__c = app.Id;
        appgoalObject.Unique_Id__c = '111';
        appgoalObject.CCA2_Account_Goal__c = accgoalObject.Id;
        insert appgoalObject;
        
        // creating question records.
        CCA2_Question__c questionObject = new CCA2_Question__c (Sequence__c = 1.0,Type__c = 'Number', Name = 'New Question', Gate__c = 2);
        insert questionObject;      
        
        //Creating goalQuestion
        CCA2_Goal_Question__c goalQuesObj = new CCA2_Goal_Question__c(CCA2_Goal__c = goalObject.id, CCA2_Question__c =  questionObject.id );
        insert goalQuesObj;
        
        //Creating Answer Object
        CCA2_Answer__c answerObject = new CCA2_Answer__c(Question__c = questionObject.id,High_Value__c=10,Low_Value__c=2);
        insert answerObject;
        
        CCA2_Answer__c answerObject2 = new CCA2_Answer__c(Question__c = questionObject.id,Low_Value__c=2);
        insert answerObject2;
        
        CCA2_Answer__c answerObject3 = new CCA2_Answer__c(Question__c = questionObject.id,High_Value__c=10);
        insert answerObject3;
        
        //Creating GoalScore Object
        CCA2_Goal_Score__c goalScoreObj = new CCA2_Goal_Score__c(Score__c = 5,Exclude__c=true, CCA2_Goals__c = goalObject.id, Answer__c = answerObject3.id);
        insert goalScoreObj;
           
        // creating response records.
        CCA2_Response__c responseObject = new CCA2_Response__c();
        responseObject.CCA2_Application__c = app.Id;
        responseObject.CCA2_Question__c    = questionObject.Id;
        responseObject.Gate__c   = 2;
        responseObject.Unique_Id__c = 'Test1012';
        insert responseObject;
        
        CCA2_Application_Goal_Score__c ags = new  CCA2_Application_Goal_Score__c();
        ags.CCA2_Response__c = responseObject.Id;
        ags.CCA2_Application_Goal__c = appgoalObject.Id;
        insert ags;
        
        AnsweringQuestionsCtrl obj = new AnsweringQuestionsCtrl();
        obj.currentQuestion = questionObject.id;
        obj.showUnanswered = true;
        obj.pagesize = 'All';
        obj.changeQuestion();
        obj.showUnanswered();
        
        obj.saveRecords();
    }

}