objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CCA2_Account_Goal__c.object
<CustomObject>
    <fields>
        <fullName>CCA2_Goal__c</fullName>
        <label>CCA2_Goal</label>
        <referenceTo>CCA2_Goal__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>CCA2_Account_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Goal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Account Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Application_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Application_Name__c</fullName>
        <formula>HYPERLINK(CCA2_Application__c ,  CCA2_Application__r.Name, &quot;_self&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCA2_Account_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CCA2_Account Goal</label>
        <referenceTo>CCA2_Account_Goal__c</referenceTo>
        <relationshipName>CCA2_Application_Goals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCA2_Application__c</fullName>
        <label>CCA2_Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>CCA2_Application_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_X_Score__c</fullName>
        <description>The final percentage match for this application to this goal</description>
        <formula>if ( Exclude__c, 0, (Total_Score__c /  CCA2_Account_Goal__r.CCA2_Goal__r.Max_Goal_Score__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The final percentage match for this application to this goal</inlineHelpText>
        <label>Total % Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Application Goal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Application Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Goal__c.object
<CustomObject>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ApplicationResultController.cls
public class ApplicationResultController{
    private string appId;
    public String appName{get;set;}

    public ApplicationResultController(){
        appId = ApexPages.currentPage().getParameters().get('id');
        List<Application__c> applst = [Select id,name from Application__c where id =: appId ];
        appName = '';
        if(applst.size()>0)
            appName = applst[0].name;
    }
    
    public list<ModleData> getData(){
       
        list<ModleData> modleList = new list<ModleData>();
        for(CCA2_Application_Goal__c gScore:[select id,Application_Name__c,CCA2_Account_Goal__r.CCA2_Goal__r.Name,Total_X_Score__c from CCA2_Application_Goal__c where CCA2_Application__c=:appId]){             
             ModleData modelObj = new ModleData(gScore.CCA2_Account_Goal__r.CCA2_Goal__r.Name,gScore.Total_X_Score__c);
             modleList.add(modelObj);
        }
        return modleList;
    }
    
    public class ModleData{
        public String goalName{get;set;}
        public decimal percentageScore{get;set;}
        public ModleData(string golName, decimal score) {
            this.goalName = golName;
            this.percentageScore = score != null ? score : 0;
        }
    }
}