objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CCA2_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CCA2_Account_Goal__c.object
<CustomObject>
    <label>Account Goal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Account Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question</description>
        <inlineHelpText>Question</inlineHelpText>
        <label>Question</label>
        <referenceTo>CCA2_Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>CCA2_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>ANS-{00000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Application_Goal__c.object
<CustomObject>
    <fields>
        <fullName>CCA2_Account_Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CCA2_Account Goal</label>
        <referenceTo>CCA2_Account_Goal__c</referenceTo>
        <relationshipName>CCA2_Application_Goals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCA2_Application__c</fullName>
        <label>CCA2_Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>CCA2_Application_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Goal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Application Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Application_Goal_Score__c.object
<CustomObject>
    <fields>
        <fullName>CCA2_Application_Goal__c</fullName>
        <label>CCA2_Application Goal</label>
        <referenceTo>CCA2_Application_Goal__c</referenceTo>
        <relationshipName>CCA2_Application_Goal_Scores</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCA2_Response__c</fullName>
        <label>CCA2_Response</label>
        <referenceTo>CCA2_Response__c</referenceTo>
        <relationshipName>CCA2_Application_Goal_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>The question for this applicationGoalScore</description>
        <formula>CCA2_Response__r.CCA2_Question__r.Name</formula>
        <inlineHelpText>The question for this applicationGoalScore</inlineHelpText>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Application Goal Score</label>
    <nameField>
        <displayFormat>AGS-{00000}</displayFormat>
        <label>CCA2_Application Goal Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Goal Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Goal_Score__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <referenceTo>CCA2_Answer__c</referenceTo>
        <relationshipLabel>Scores By Goal</relationshipLabel>
        <relationshipName>Goal_Scores</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCA2_Goals__c</fullName>
        <label>CCA2_Goal</label>
        <referenceTo>CCA2_Goal__c</referenceTo>
        <relationshipLabel>Answer Scores</relationshipLabel>
        <relationshipName>CCA2_Goal_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Goal Score</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Goal Score  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goal Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Question__c.object
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CCA2_Response__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>CCA2_Application__r.Account__r.Name</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCA2_Application__c</fullName>
        <label>CCA2_Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>CCA2_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCA2_Question__c</fullName>
        <label>CCA2_Question</label>
        <referenceTo>CCA2_Question__c</referenceTo>
        <relationshipName>CCA2_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Response</label>
    <nameField>
        <displayFormat>RESP-{0}</displayFormat>
        <label>CCA2_Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ApplicationByClassificationController.cls
/*
                Name:      ApplicationByClassificationController
                Author:    
                Date:      28 Jan 2015
                Description: Controller to Group the applications According to the classification 
*/
public class ApplicationByClassificationController{
    public List<MainModel> mainModelList {get;set;}
    public string agsId;
    public String questxt{get;set;}
    
    //Constructor
    public ApplicationByClassificationController(){
        questxt = '';
        integer size = 15;
        mainModelList = new List<MainModel>();
        agsId = ApexPages.currentPage().getParameters().get('id');
        if(agsId!=null && agsId.trim().length()>0){
            
            list<CCA2_Application_Goal_Score__c> tempAGSList = [SELECT Id, Question__c,CCA2_Application_Goal__r.CCA2_Account_Goal__r.Account__r.Id, CCA2_Response__c, CCA2_Response__r.CCA2_Question__c FROM CCA2_Application_Goal_Score__c WHERE Id =: agsId];
            
            if(tempAGSList.size()>0){
                questxt = tempAGSList[0].Question__c;
                set<string> appIds = new set<string>();
                set<string> AccountIds = new set<string>();
                decimal maxQusScore = 0;
                
                for(CCA2_Application_Goal_Score__c ags : tempAGSList){
                    AccountIds.add(ags.CCA2_Application_Goal__r.CCA2_Account_Goal__r.Account__r.Id);
                }
                system.debug('####AccountIds--->'+AccountIds);
                AggregateResult[] groupedResults = [SELECT CCA2_Goals__c, Answer__r.Question__c, MAX(Score__c)maxScore 
                                                    FROM CCA2_Goal_Score__c 
                                                    WHERE Answer__r.Question__c =: tempAGSList[0].CCA2_Response__r.CCA2_Question__c 
                                                    GROUP BY Answer__r.Question__c, CCA2_Goals__c];
                
                if(groupedResults.size()>0){
                    for(AggregateResult agg : groupedResults){
                        string temp3 = ''+agg.get('maxScore')!=null ? ''+agg.get('maxScore') : '0';
                        maxQusScore += decimal.valueOf(temp3);
                    }
                }
            
                /*for(CCA2_Response__c res : [SELECT Id, CCA2_Application__c, CCA2_Question__c FROM CCA2_Response__c WHERE Id =: tempAGSList[0].CCA2_Response__c]){
                    appIds.add(res.CCA2_Application__c);
                }*/
                
                if(AccountIds.size()>0){
                    List<Application__c> applst = [SELECT name,ID, Classification__c 
                                                  FROM Application__c  
                                                  WHERE Account__c IN: AccountIds                                            
                                                  ORDER BY  Classification__c ASC LIMIT 1000];
                    for(Application__c app : applst){
                         appIds.add(app.Id);
                    }
                    system.debug('####appIds--->'+appIds);
                    if(appIds.size()>0){
                        map<string, decimal> appTotScoreMap = new map<string, decimal>();
                        for(AggregateResult agg : [SELECT CCA2_Application_Goal__r.CCA2_Application__c applId, SUM(score__c)totScore
                                                   FROM CCA2_Application_Goal_Score__c 
                                                   WHERE CCA2_Application_Goal__r.CCA2_Application__c IN: appIds 
                                                   AND CCA2_Response__c =: tempAGSList[0].CCA2_Response__c
                                                   Group by  CCA2_Application_Goal__r.CCA2_Application__c]){
                            if(!appTotScoreMap.containsKey(''+agg.get('applId'))){
                                string temp = ''+agg.get('totScore')!=null ? ''+agg.get('totScore') : '0';
                                appTotScoreMap.put(''+agg.get('applId'), decimal.valueOf(temp));
                            }
                            /*
                            if(!appTotScoreMap.containsKey(''+agg.get('applId'))){
                                string temp = ''+agg.get('maxScore')!=null ? ''+agg.get('maxScore') : '0';
                                appTotScoreMap.put(''+agg.get('applId'), decimal.valueOf(temp));
                            }else if(appTotScoreMap.containsKey(''+agg.get('applId'))){
                                string temp2 = ''+agg.get('maxScore')!=null ? ''+agg.get('maxScore') : '0';
                                appTotScoreMap.put(''+agg.get('applId'), appTotScoreMap.get(''+agg.get('applId'))+decimal.valueOf(temp2));
                            }*/
                        }
                    
                        Map<String,List<Application__c>> applicationMap = new Map<String,List<Application__c>>();
                        for(Application__c app : [SELECT name,  Classification__c 
                                                  FROM Application__c 
                                                  WHERE Id IN: appIds
                                                  ORDER BY  Classification__c ASC LIMIT 1000]){
                            List<Application__c> appList = applicationMap.get(app.Classification__c);
                            if(appList == null){
                                appList =  new List<Application__c>();
                            }
                            appList.add(app);
                            applicationMap.put(app.Classification__c, appList);
                        }
                        for(String classification : applicationMap.keySet()){
                            MainModel mModel = new MainModel();
                            mModel.classification = classification;
                            mModel.applicationModelList = new List<ApplicationListModel>();
                            Integer i = 1;
                            ApplicationListModel appModelList = new ApplicationListModel();
                            for(Application__c app : applicationMap.get(classification)){
                                    ApplicationModel appModel = new ApplicationModel();
                                    appModel.appName = app.Name;
                                    if(appTotScoreMap.containsKey(app.Id)){
                                        appModel.percentScore = appTotScoreMap.get(app.Id)>0 && maxQusScore>0 ? appTotScoreMap.get(app.Id)/maxQusScore*100 : 0;
                                    }
                                    
                                    appModelList.applicationList.add(appModel);
                                    if(math.mod(i,size)==0){
                                        mModel.applicationModelList.add(appModelList);
                                        appModelList = new ApplicationListModel();   
                                    }
                                    i++;     
                            }
                            for(integer p=0;p <= size-math.mod(i,size);p++){
                                appModelList.applicationList.add(new ApplicationModel());
                            }
                            if(math.mod(i,size)!=1){
                                 mModel.applicationModelList.add(appModelList);
                            }
                            mainModelList.add(mModel);
                        }
                    }
                }
            }
        }
    }
    
    public class MainModel{
        public String classification {get;set;}
        public List<ApplicationListModel> applicationModelList {get;set;}
        public MainModel(){
            applicationModelList = new List<ApplicationListModel>();
        }
    }
    public class ApplicationListModel{
        public List<ApplicationModel> applicationList {get;set;}
        public ApplicationListModel(){
            applicationList = new List<ApplicationModel>();
        }
    }
    public class ApplicationModel{
        public string appName{get;set;}
        public decimal percentScore{get;set;}
        
        public ApplicationModel(){
            percentScore = 0;
        }
    }
}