objects/Case.object
<CustomObject>
    <fields>
        <fullName>Actual_Hours__c</fullName>
        <label>Actual Hours</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Requirement</fullName>
        <active>true</active>
        <label>Requirement</label>
    </recordTypes>
</CustomObject>

objects/Project_Request__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Hours__c</fullName>
        <label>Actual Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Project Requests</relationshipLabel>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Ready For Review</fullName>
                </value>
                <value>
                    <fullName>Re-Opened</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Request</label>
    <nameField>
        <label>Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestUpdateCaseOnPRComplete.cls
public class TestUpdateCaseOnPRComplete {


	@isTest
	public static void updateCaseTest() {
		RecordType rt = [select id from recordType where sObjectType = 'Case' and name = 'Requirement' limit 1];
		Case c = new Case();
		c.recordTypeid = rt.id;
		c.origin = 'Phone';
		c.status = 'New';
		insert c;
		
		Project_Request__c pr = new Project_Request__c();
		pr.case__c = c.id;
		pr.actual_hours__c = 12.0;
		pr.status__c = 'Closed';
		insert pr;
		
		c = [select id, actual_hours__c from case where id = :c.id]; 
		
		System.assertEquals(pr.actual_hours__c, c.actual_hours__c, 'Case and PR do not have the same hours');
	}
}