objects/Case.object
<CustomObject>
    <fields>
        <fullName>Actual_Hours__c</fullName>
        <label>Actual Hours</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>A piece of functionality being worked on</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>What is this project trying to achieve</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>deployed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this project deployed?</description>
        <label>Deployed</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Request__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Hours__c</fullName>
        <label>Actual Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Project Requests</relationshipLabel>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completion_Summary__c</fullName>
        <label>Completion Summary</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Developer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Requests</relationshipLabel>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Requests</relationshipLabel>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Ready For Review</fullName>
                </value>
                <value>
                    <fullName>Re-Opened</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Request</label>
    <nameField>
        <label>Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Card__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Day__c</fullName>
        <label>Day</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <label>Developer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_Ending__c</fullName>
        <label>Month Ending</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Request</label>
        <referenceTo>Project_Request__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week_Ending__c</fullName>
        <description>The date of the friday of the week</description>
        <label>Week Ending</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Time Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestTimeCardEntryController.cls
@isTest
public class TestTimeCardEntryController{
    @isTest
    private static void checkTimeCardEntryController(){
       account acc=new account();
       acc.name='Account First';
       insert acc;
        contact con=new contact();
        con.firstname='aslam';
        con.lastname='bari';
        con.accountId=acc.id;
        insert con;
        Project__c prjObj=new Project__c();
       prjObj.Account__c=acc.id;
       prjObj.Customer_Owner__c=con.id;
       prjObj.deployed__c=true;   
       prjObj.Description__c='aaa';
       insert prjObj;
        case caseObj=new case();
        caseObj.Origin='Email';
       caseObj.Status='New';
       caseObj.subject='aaa';
       caseObj.description='www';
       caseObj.project__c=prjObj.id;
       insert caseObj;
           Project_Request__c prjRequestObj=new Project_Request__c();
           prjRequestObj.Actual_Hours__c=10;
           prjRequestObj.Case__c=caseObj.id;
           prjRequestObj.Completion_Summary__c='aaa';
           prjRequestObj.Description__c='ww';
           prjRequestObj.Developer__c=con.id;
           prjRequestObj.Project__c=prjObj.id;
           prjRequestObj.Status__c='New';
           insert prjRequestObj;
        Time_Card__c timeCardObj=new Time_Card__c();
        timeCardObj.Comments__c='abc';
        timeCardObj.Day__c=date.today();
        timeCardObj.Developer__c=prjRequestObj.Developer__c;
        timeCardObj.Hours__c=2.0;
        timeCardObj.Month_Ending__c=date.today();
        timeCardObj.Project_Request__c=prjRequestObj.id;
        timeCardObj.Week_Ending__c=date.today().toStartOfWeek().addDays(5);
        insert timeCardObj;
        TimeCardEntryController timeCardEntryObj=new TimeCardEntryController(new ApexPages.StandardController(timeCardObj));
        timeCardEntryObj.retrieveTimeCards();
        timeCardEntryObj.setTimeCardsList();
        timeCardEntryObj.addTimeCard();
        timeCardEntryObj.saveTimeCards() ;
    }
}