objects/Case.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>A piece of functionality being worked on</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>What is this project trying to achieve</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Request__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Project Requests</relationshipLabel>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Requests</relationshipLabel>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Ready For Review</fullName>
                </value>
                <value>
                    <fullName>Re-Opened</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Request</label>
    <nameField>
        <label>Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreatePRController.cls
public class CreatePRController {
  
  public Case currentCase {get;set;}
  public Project_Request__c projectRequest {get;set;}
  
  public CreatePRController(ApexPages.StandardController controller){
    currentCase = (Case)controller.getRecord();
    currentCase = [select id, subject, description, project__c from case where id = :currentCase.id];
  }

 
  public Pagereference createPR(){
    try{
      List<project_Request__c> prs = [select id from project_request__c where case__c = :currentCase.id ];
      project_Request__c projectRequest = new Project_Request__c();
      if (prs.size() == 0) {
      	 projectRequest.description__c = currentCase.description;
      	 projectRequest.project__c = currentCase.project__c;
      	 projectRequest.status__c = 'New';
      	 projectRequest.name = currentCase.subject;
      	 projectRequest.case__c = currentCase.id;
      	 insert projectRequest;
      } else {
      	 projectRequest = prs.get(0);
      }
      
      ApexPages.addMessage(new ApexPages.Message(Apexpages.Severity.INFO ,'PR has been created with is '+ projectRequest.id));
      return new Pagereference('/'+ projectRequest.Id);
    }catch(Exception ex){
      ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR,ex.getMessage()));
    }  
    return null;   
  }
  
  
}