objects/CCA2_Application_Goal__c.object
<CustomObject>
    <fields>
        <fullName>CCA2_Application__c</fullName>
        <label>CCA2_Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>CCA2_Application_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Goal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CCA2_Application Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Application_Goal_Score__c.object
<CustomObject>
    <fields>
        <fullName>CCA2_Application_Goal__c</fullName>
        <label>CCA2_Application Goal</label>
        <referenceTo>CCA2_Application_Goal__c</referenceTo>
        <relationshipName>CCA2_Application_Goal_Scores</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCA2_Response__c</fullName>
        <label>CCA2_Response</label>
        <referenceTo>CCA2_Response__c</referenceTo>
        <relationshipName>CCA2_Application_Goal_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Goal Score</label>
    <nameField>
        <displayFormat>AGS-{00000}</displayFormat>
        <label>CCA2_Application Goal Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Goal Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CCA2_Response__c.object
<CustomObject>
    <label>Response</label>
    <nameField>
        <displayFormat>RESP-{0}</displayFormat>
        <label>CCA2_Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ApplicationGoalScoreHelper.cls
public with sharing class ApplicationGoalScoreHelper {
    public Static boolean stopApplicationGoalTrigger = false;

    public static void MarkAsCompleted(set<string> appGoalIds){
        List<CCA2_Application_Goal__c> updateAppGoals = new List<CCA2_Application_Goal__c>();
        
        if(appGoalIds.size()>0){
            set<string> appIds = new set<string>();
            for(CCA2_Application_Goal__c appGoal : [SELECT Id, CCA2_Application__c FROM CCA2_Application_Goal__c
                                                   WHERE Id IN: appGoalIds]){
                                                   
                appIds.add(appGoal.CCA2_Application__c);
            }
            
            List<CCA2_Application_Goal__c> tempAppGoals = [SELECT Id, Completed__c,
                                                           (SELECT Id
                                                            FROM CCA2_Application_Goal_Scores__r 
                                                            WHERE CCA2_Response__r.Answer__c =: null)
                                                           FROM CCA2_Application_Goal__c
                                                           WHERE CCA2_Application__c IN: appIds]; 
                                                           
            if(tempAppGoals.size()>0){
                for(CCA2_Application_Goal__c ag : tempAppGoals){
                    if(ag.CCA2_Application_Goal_Scores__r.size()==0){
                        CCA2_Application_Goal__c tempAppGoal = ag;
                        tempAppGoal.Completed__c = true;
                        updateAppGoals.add(tempAppGoal);
                    }
                }
                if(updateAppGoals.size()>0){
                    update updateAppGoals;
                }
            }                                               
        }                                                           
        //We're only interested in AGSs where the score was updated
        //get the AGs associated with these score-updated AGSs
        //return the AGs that have no unswered AGS records associated with them
        //return result;
    }
}