objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly Rate</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Hours_Worked__c</fullName>
        <label>Total Hours Worked</label>
        <summarizedField>Time_Card__c.Hours__c</summarizedField>
        <summaryForeignKey>Time_Card__c.Developer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{00000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TotalTimeCardInfoController.cls
public with sharing class TotalTimeCardInfoController {
	
	public string accountId;
	public Account thisAccount;
	public double totalTimeCards {get;set;}
	public double totalPayments {get;set;}
	public double totalOwed {get;set;}
	
	public TotalTimeCardInfoController (ApexPages.StandardController stdController) {
		accountID = stdController.getId();
		thisAccount = [select id from Account where id = :accountId limit 1];
		system.debug('accountid is ' + accountID);
		totalTimeCards = 0;
		List<Contact> contacts = [select id, Total_Hours_Worked__c, hourly_rate__c from Contact where accountid = :accountId];
		for (Contact cont : contacts) {
			if (cont.Total_Hours_Worked__c != null && cont.hourly_Rate__c !=null) {
				System.debug('hours/rate is ' + cont.Total_Hours_Worked__c + '/' + cont.hourly_Rate__c);
				totalTimeCards += cont.Total_Hours_Worked__c * cont.hourly_Rate__c;
			}
		}
		totalPayments = 0;
		List<Payment__c> payments = [select id, amount__c, vendor__c from Payment__c where vendor__c = :accountId];
		for (Payment__c pay : payments) {
			totalPayments += pay.amount__c;
		}
		totalOwed = totalTimeCards - totalPayments;
	}
	
	

	
	
}