objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly Rate</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Paid__c</fullName>
        <label>Date Paid</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{00000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestTotalTimeCardInfoController.cls
/*
           Name : TestTotalTimeCardInfoController
     Class Name : TotalTimeCardInfoController 
         Author :
           Date : 3 April 2015 
    Description : Testing TotalTimeCardInfoController controllelr in this test class
*/
@isTest
public class TestTotalTimeCardInfoController{
    
    // testing method
    @isTest private static void startTest(){
        // insert account test record
        account a = new account();
        a.name = 'Defy';
        insert a;
        System.assertEquals(a.name ,'Defy');
        ApexPages.StandardController sc = new ApexPages.StandardController(a);
        //insert contact test record
        contact con = new contact();
        con.lastname = 'Jim aurthor';
        con.accountid = a.id;
        con.hourly_rate__c = 10;
        insert con;
        System.assertEquals(con.accountid , a.id);
        // insert payment test record 
        payment__c pay = new payment__c();
        pay.amount__c = 1000;
        pay.vendor__c = a.id; 
        pay.Date_Paid__c = date.today();
        // class instance
        TotalTimeCardInfoController ttcc = new TotalTimeCardInfoController(sc);
    }
}