objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Normalize_Phone__c</fullName>
        <formula>SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE(Phone, &apos;.&apos;, &apos;&apos;)  , &apos; &apos;, &apos;&apos;)  , &apos;-&apos;, &apos;&apos;)  , &apos;)&apos;, &apos;&apos;)  , &apos;(&apos;, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Normalize Phone</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Twilio_Call_History__c.object
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Picked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Twilio Call History</label>
    <nameField>
        <displayFormat>TWL-{00000}</displayFormat>
        <label>Twilio Call History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Twilio Call Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Normalize_Phone__c</fullName>
        <formula>SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE(Phone, &apos;.&apos;, &apos;&apos;)  , &apos; &apos;, &apos;&apos;)  , &apos;-&apos;, &apos;&apos;)  , &apos;)&apos;, &apos;&apos;)  , &apos;(&apos;, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Normalize Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Twilio_Number__c</fullName>
        <label>Twilio Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CallChecker.cls
public class CallChecker{
    public string userphone {get;set;}
    public string contactId {get;set;}
    public string log {get;set;}
    public CallChecker(){
        userphone = [Select Id, Twilio_Number__c from User where id=:UserInfo.getUserId()].Twilio_Number__c;
        userphone = userphone.trim();
        contactId = '';
    }
    
    public PageReference callagain(){
        List<Twilio_Call_History__c> callList =  [SELECT Id, To__c, From__c, Status__c from Twilio_Call_History__c WHERE Status__c ='New' and To__c =:userphone order by createddate desc limit 1];
        log = callList.size() + '-ttt';
        if(callList.size() > 0){
            Twilio_Call_History__c tch = callList.get(0);
            List<Contact> contactList = [SELECT Id from Contact where Normalize_Phone__c =:tch.From__c LIMIT 1];
            if(contactList.size() > 0){
                contactId = contactList.get(0).Id;
            }
            tch.Status__c = 'Picked';
            update tch;
        }
        return null;
    }
    
    public PageReference handledcall(){ 
        contactId = '';
        return null;
    }
}