objects/Expertise__c.object
<CustomObject>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Expertise</label>
    <nameField>
        <label>Expertise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expertises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestSiteExpertiseController.cls
public class TestSiteExpertiseController{
    @isTest
    private static void testController(){
        Expertise__c exp = new Expertise__c();
        exp.Name='test';
        exp.Details__c='This is \n detail';
        insert exp;
        SiteExpertiseController sch = new SiteExpertiseController();
        ApexPages.currentPage().getParameters().put('id',exp.id);
        SiteExpertiseController sch1 = new SiteExpertiseController();
        
    }
}