objects/Expertise__c.object
<CustomObject>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tag__c</fullName>
        <label>Tag</label>
        <type>TextArea</type>
    </fields>
    <label>Expertise</label>
    <nameField>
        <label>Expertise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expertises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SiteHomeController.cls
public class SiteHomeController{
    public List<Expertise__c> expertises {get;set;}
    public SiteHomeController(){
        expertises = [SELECT Name, Tag__c, Details__c, Order__c from Expertise__c ORDER BY Order__c ASC LIMIT 3];
    
    }
    
    public Expertise__c getFirstColumn(){
        return expertises.get(0);
    }
    
    public Expertise__c getMiddleColumn(){
        return expertises.get(1);
    }
    
    public Expertise__c getLastColumn(){
        return expertises.get(2);
    }

}