objects/Gift__c.object
<CustomObject>
    <fields>
        <fullName>Expected_Delivery__c</fullName>
        <label>Expected Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Value__c</fullName>
        <label>Gift Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Giver_Reddit_Username__c</fullName>
        <label>Giver (Reddit Username)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IP_Address__c</fullName>
        <label>IP Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Receiver</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Person__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Receiver</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Gifts</relationshipLabel>
        <relationshipName>Gifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reported as Purchased</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Gift</label>
    <nameField>
        <label>Gift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Gift_Reported__c.object
<CustomObject>
    <fields>
        <fullName>Child__c</fullName>
        <label>Child</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Gifts Reported (Child)</relationshipLabel>
        <relationshipName>Gifts_Reported1</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Gift_Value__c</fullName>
        <label>Gift Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <label>Gift</label>
        <referenceTo>Gift__c</referenceTo>
        <relationshipLabel>Gifts Reported</relationshipLabel>
        <relationshipName>Gifts_Reported</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Gift Reported</label>
    <nameField>
        <displayFormat>GR-{00000}</displayFormat>
        <label>Gift Reported</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gifts Reported</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Person__c.object
<CustomObject>
    <fields>
        <fullName>IP_Address__c</fullName>
        <label>IP Address</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver__c</fullName>
        <label>Receiver</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Childs</relationshipLabel>
        <relationshipName>Persons</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reddit_Username__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Reddit Username</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Redit_Username_Normal__c</fullName>
        <formula>lower(Reddit_Username__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Redit Username Normal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Status__c</fullName>
        <label>Registration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registration in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Action Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RAOC People</pluralLabel>
    <recordTypes>
        <fullName>Admin</fullName>
        <active>true</active>
        <label>Admin</label>
    </recordTypes>
    <recordTypes>
        <fullName>Child</fullName>
        <active>true</active>
        <label>Child</label>
    </recordTypes>
    <recordTypes>
        <fullName>Receiver</fullName>
        <active>true</active>
        <label>Receiver</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AssignGiftCtrl.cls
public class AssignGiftCtrl{
    public Gift__c newGift{get;set;}
    public String receiverRedditName{get;set;}
    public List<String> selectedChilds{get;set;}
    public List<Selectoption> childOptions{get;set;}
    public List<Selectoption> receiverOptions{get;set;}
    public Attachment newAttach{get;set;}
    public String errorMsg{get;set;}
    public boolean thanks {get;set;} 
    private String receiverId;
    private String giverId;
    private Person__c receiver = new Person__c();
    public string selectedReceiver {get;set;}
    
    public AssignGiftCtrl(){        
        receiverId = null;
        receiverRedditName ='';
        errorMsg = '';
        selectedChilds = new List<String>();
        receiverOptions = new List<SelectOption>();
        childOptions = new List<SelectOption>();
        newAttach = new Attachment();
        newGift = new Gift__c();
    }
    
    //Init for Gift_Given page
    public PageReference initForAssignGiftCtrl(){
        if( CookieHelperController.fetchCookieValue() != null && CookieHelperController.fetchCookieValue().length() != 0 ){
            List<Person__c> tempList = [Select Id, recordtype.name From Person__c Where id =: CookieHelperController.fetchCookieValue() limit 1];
            if ( tempList.size() > 0 ){
                if (tempList[0].recordtype.name == 'Admin' ){
                    return page.homepage;
                }
            }
        } 
        String hostVal = ApexPages.currentPage().getHeaders().get('Host');
        String urlVal = Apexpages.currentPage().getUrl();
        if(test.isRunningTest()){
            urlVal='/apex/loginpage';
        }
        if( hostVal == 'tfs-tfs.cs22.force.com' || test.isRunningTest() ){
            String reDirectURL = 'http://tfs.force.com/raoc'+urlVal.substring(5,urlVal.length());
            pagereference pg = new pagereference(reDirectURL);
            pg.setredirect(true);
            return pg;
        }
        return null;
    }
    
    //Find Receivers
    public void findReceiver(){
        receiverOptions.clear();
        childOptions = new List<SelectOption>();
        if(receiverRedditName .trim().length() > 0 ){            
            List<Person__c> tempList = [Select Id, Name,Reddit_Username__c From Person__c Where RecordType.Name = 'Receiver' and Redit_Username_Normal__c like : '%'+ receiverRedditName + '%' and Registration_Status__c in('Approved','Registration in Progress') ];
            if( tempList.size() > 0 ){
                for(person__c rec : tempList ){
                    receiverOptions.add(new selectoption(rec.id,rec.Reddit_Username__c));
                }
                selectedReceiver = tempList[0].id;
                receiverId =  tempList[0].id;
                findChildrens();
            }
        }
    }
    
    //Find childerns of giving receiver reddit username
    public void findChildrens(){
        receiverId = selectedReceiver ;
        List<Person__c> tempList = [ Select Id,Name From Person__c Where RecordType.Name = 'Child' and Receiver__c =: receiverId  ];
        childOptions = new List<SelectOption>();
        selectedChilds = new List<String>();
        if( tempList.size()>0 ){
            for(Person__c child : tempList ){
                childOptions.add(new SelectOption((String)child.Id,child.Name));
            }
        }
    }
    
    //Functionality of send gifts to receiver
    public void sendGift(){ 
        thanks = false;   
        if( validate() ){
            try{
                newGift.IP_Address__c = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP') ;
                newGift.Receiver__c = receiverId;
                newGift.Status__c = 'Reported as Purchased';
                newGift.Name = newGift.Name.length() > 80 ? newGift.Name.subString(0,79) : newGift.Name;
                insert newGift;      
                       
                if(newAttach.Body != null){
                    newAttach.ParentId = newGift.Id;
                    insert newAttach;
                    newAttach = new Attachment();
                }
            }catch(Exception exp){}
            
            decimal valuePerChild = newGift.Gift_Value__c / selectedChilds .size();
            List<Gift_Reported__c> newGiftsReported = new List<Gift_Reported__c>();
            for(String childId : selectedChilds){
                Gift_Reported__c gr = new Gift_Reported__c();
                gr.Gift__c = newGift.Id;
                gr.Gift_Value__c = valuePerChild;
                gr.Child__c = childId;
                newGiftsReported.add(gr);
            }
            if(newGiftsReported.size()>0){
                try{
                    insert newGiftsReported;
                }catch(Exception exp){}
            }
            thanks = true ;
            receiverId = null;
            receiverRedditName ='';
            errorMsg = '';
            selectedChilds = new List<String>();
            childOptions = new List<SelectOption>();
            receiverOptions = new List<SelectOption>();
            newAttach = new Attachment();
            newGift = new Gift__c();   
        }
    }
    
    //Check validation
    private boolean validate(){
        errorMsg ='';   
        system.debug('### Username :'+newGift.Giver_Reddit_Username__c);
        if (newGift.Giver_Reddit_Username__c == null || newGift.Giver_Reddit_Username__c.trim().length()==0){
            errorMsg += '&#8226; Please enter Reddit Username <br/>';
        }
        if ( newGift.Name == null || newGift.Name.trim().length()==0){
            errorMsg += '&#8226; Please enter Gift Name <br/>';
        }
        if ( newGift.Gift_Value__c  == null){
            errorMsg += '&#8226; Please enter Gift Value <br/>';
        }
        if (newGift.Gift_Value__c  <= 0){
            errorMsg += '&#8226; Gift Value shoud be greater then zero <br/>';
        }
        if ( newGift.Expected_Delivery__c  != null && newGift.Expected_Delivery__c < System.Today() ){
            errorMsg += '&#8226; You cannot enter past date. <br/>';
        }
        if ( selectedChilds .size() == 0 ){
            errorMsg += '&#8226; Please select at least one child from child list';
        }
        
        if(errorMsg.trim().length() > 0 ){
            return false;
        }
        return true;
    }
}