objects/Person__c.object
<CustomObject>
    <fields>
        <fullName>Date_Of_Approval__c</fullName>
        <label>Date Of Approval</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reddit_Username__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Reddit Username</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Registration_Status__c</fullName>
        <label>Registration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registration in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Action Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RAOC People</pluralLabel>
    <recordTypes>
        <fullName>Receiver</fullName>
        <active>true</active>
        <label>Receiver</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RegisteredUserController.cls
public class RegisteredUserController{
    public list<person__c> listPerson {get;set;}
    public integer listSizeUnRec{get;set;}
    public integer offsetVar {get;set;}
    
    public void init(){
        offsetVar = 0;
        listSizeUnRec= [select id from person__c where recordtype.name = 'Receiver' and Registration_Status__c = 'Approved' ].size();
        fetchApprovedUsers();
    }
    
    public void next(){
        offsetVar += 10;
        fetchApprovedUsers();
    }
    
    public void prev(){
        offsetVar -= 10;
        fetchApprovedUsers();
    }
    
    public void first(){
        offsetVar = 0;
        fetchApprovedUsers();
    }
    
    public void last(){
        offsetVar = listSizeUnRec-math.mod(listSizeUnRec,10);
        fetchApprovedUsers();
    }
    
    private void fetchApprovedUsers(){
        String query = 'select Reddit_Username__c from person__c where recordtype.name=\'Receiver\' and Registration_Status__c=\'Approved\' order by Date_Of_Approval__c desc';
        listPerson = Database.Query(query);
    }
}