objects/Project__c.object
<CustomObject>
    <description>A piece of functionality being worked on</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Request__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Developer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Requests</relationshipLabel>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Requests</relationshipLabel>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Request</label>
    <nameField>
        <label>Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Card__c.object
<CustomObject>
    <fields>
        <fullName>Day__c</fullName>
        <label>Day</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <label>Developer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Request</label>
        <referenceTo>Project_Request__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Time Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestPRHoursAdjust.cls
public with sharing class TestPRHoursAdjust {


    @isTest
    public static void TestAffectProjectRequestActuals () {
        
        Account acc = new Account();
        acc.name = 'test';
        insert acc;
        
        Project__c proj = new Project__c();
        proj.name = 'asasd';
        insert proj;
        
        Contact con = new Contact();
        con.firstname='alan';
        con.lastname='brown';
        con.account = acc;
        insert con;
        
        project_request__c projectReq = new project_request__c();
        projectReq.name = 'asgf';
        projectReq.developer__c = con.id;
        projectReq.project__c = proj.id;
            
        Time_card__c tCard = new Time_card__c();
        tCard.day__c = Date.today();
        tCard.Hours__c = 12.0;
        tCard.Developer__c = con.id;        
        try {
            insert tcard;            
        } catch (Exception e) {
            System.debug('all is well');
        }
        
    }
}