objects/Project__c.object
<CustomObject>
    <description>A piece of functionality being worked on</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Request__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Developer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Requests</relationshipLabel>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Requests</relationshipLabel>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Request</label>
    <nameField>
        <label>Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Card__c.object
<CustomObject>
    <fields>
        <fullName>Day__c</fullName>
        <label>Day</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <label>Developer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Request</label>
        <referenceTo>Project_Request__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week_Ending__c</fullName>
        <description>The date of the friday of the week</description>
        <label>Week Ending</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Time Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestaffectProjectRequestActuals.cls
/*
        Name        :  TestaffectProjectRequestActuals
        Author      :
        Date        :  04/04/2015
        Description :  This test class for 'affectProjectRequestActuals' class.
*/

@isTest
public class TestaffectProjectRequestActuals{
    @isTest
    private static void affectProjectTest(){
        // Insert account object
            Account acc = new Account(Name = 'TestAccount');
            insert acc;
        // Insert contact object
            Contact con = new Contact(Lastname = 'TestContact', AccountId = acc.id);
            insert con;
        // Insert Project object
            Project__c pro = new Project__c(Name = 'TestProject');
            insert pro;
        // Insert Project request object
            Project_Request__c pr = new Project_Request__c(Project__c = pro.id, Developer__c = con.id, Name = 'TestSummry');
            insert pr;
        // Insert Time Card object
            Time_Card__c tc = new Time_Card__c(Hours__c = 5, Day__c = system.Today(), Week_Ending__c = system.Today().addDays(3),Developer__c = con.id,Project_Request__c = pr.id);
            insert tc;
        // Update time card object
            tc.Hours__c = 6;
            update tc;
        // Delete time card object
            delete tc;
    }
}