objects/Project_Request__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Developer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Requests</relationshipLabel>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Request</label>
    <nameField>
        <label>Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Card__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Day__c</fullName>
        <label>Day</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <label>Developer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Request</label>
        <referenceTo>Project_Request__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week_Ending__c</fullName>
        <description>The date of the friday of the week</description>
        <label>Week Ending</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Time Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TimeCardEntryController.cls
public with sharing class TimeCardEntryController {
    
    public List<Time_card__c> timecards {get;set;}
    public Time_card__c newTimeCard {get;set;}
    public Time_card__c tempTimeCard;
    public boolean haveTimecards {get;set;}
    

    public TimeCardEntryController(ApexPages.StandardController stdController) {
        newTimeCard = new Time_Card__c();
        timeCards = new List<Time_Card__c>();
        newTimeCard.Week_Ending__c = Date.today().toStartOfWeek().addDays(5);
        
        Contact dev = [select id, firstname, name from contact where firstName='aslam' ];
        newTimeCard.Developer__c = dev.id;
        haveTimecards = false;
        
        setTimeCardsList();
    }
    
    public PageReference retrieveTimeCards() {
         
        if (newTimeCard.developer__c == null) {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please Enter the Developer who you are entering timecards for');
            ApexPages.addMessage(msg);      
        } else 
            setTimeCardsList(); 
        haveTimecards = timeCards.size() > 0;

        return null;
    }
    
    
    
    public void setTimeCardsList() {
        newTimeCard.week_ending__c = newTimeCard.week_ending__c.toStartOfWeek().addDays(5);
        timeCards = [select id, Name, hours__c, week_ending__c, developer__c, developer__r.name,
                    day__c, Project_request__c, project_request__r.name, comments__c
                    from time_card__c where week_ending__c = :newTimeCard.week_ending__c and developer__c = :newTimeCard.developer__c
                    order by day__c asc];                        
    }
    
    public PageReference addTimeCard() {
        try {
        
            insert newTimeCard;
            
            setTimeCardsList();
            newTimeCard.hours__c = null;
            newTimeCard.id = null;
            newTimeCard.comments__c = null;
                        
        } catch (Exception e) {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage());
            ApexPages.addMessage(msg);
        }
        return null;
    }
    
    public PageReference saveTimeCards() {
        try {
            update timeCards;
                
            setTimeCardsList();
            haveTimecards = timeCards.size() > 0;       
        } catch (Exception e) {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage());
            ApexPages.addMessage(msg);
        }
        return null;
    }
    
    
}