objects/Twilio_Call_History__c.object
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Picked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Twilio Call History</label>
    <nameField>
        <displayFormat>TWL-{00000}</displayFormat>
        <label>Twilio Call History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Twilio Call Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Normalize_Phone__c</fullName>
        <formula>SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE(Phone, &apos;.&apos;, &apos;&apos;)  , &apos; &apos;, &apos;&apos;)  , &apos;-&apos;, &apos;&apos;)  , &apos;)&apos;, &apos;&apos;)  , &apos;(&apos;, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Normalize Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Twilio_Number__c</fullName>
        <label>Twilio Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TwilioCallHandler.cls
public class TwilioCallHandler{
    public string caller {get;set;}
    public string called {get;set;}
    public string phoneNumber {get;set;}
    public TwilioCallHandler(){
        caller = ApexPages.currentPage().getParameters().get('Caller');
        if (caller.startsWith('+1'))
			caller = caller.substring(2);
        called = ApexPages.currentPage().getParameters().get('Called');
        if (called.startsWith('+1'))
			called = called.substring(2); 
        List<User> lstUsers = [SELECT Twilio_Number__c, Normalize_Phone__c from User where Twilio_Number__c =:called];
        if(lstUsers.size() > 0){
            phoneNumber = lstUsers.get(0).Normalize_Phone__c;
        }
    }
    
    public PageReference doInit(){
        Twilio_Call_History__c tch = new Twilio_Call_History__c();

        tch.To__c = called;          
        tch.From__c = caller;      
        tch.Status__c = 'New';
        insert tch;    
        return null;
    }
}