objects/Twilio_Call_History__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Picked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Twilio Call History</label>
    <nameField>
        <displayFormat>TWL-{00000}</displayFormat>
        <label>Twilio Call History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Twilio Call Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Twilio_Number__c</fullName>
        <label>Twilio Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestCallChecker.cls
public class TestCallChecker{
    @isTest
    private static void testController(){
        User u = [Select id, Twilio_Number__c from User where id=:UserInfo.getUserId()];
        Twilio_Call_History__c twh = new Twilio_Call_History__c();
        twh.Status__c = 'New';
        twh.To__c = u.Twilio_Number__c;
        insert twh;
        CallChecker cc = new CallChecker();
        cc.callagain();
        cc.handledCall();    
    }



}